### ISSUE TITLE
Possible speedup for nodejs tests

### ISSUE THREAD

**Issue by lambdaq** [MagicStack/vmbench#1]
For nodejs benchmark, consider add this

```
require('http').globalAgent.maxSockets = 64;
```

or change it to 128.

The default is 5 so its pretty limited.

Ref: https://www.reddit.com/r/programming/comments/4hqd1b/uvloop_make_python_networking_great_again/d2rzm35

**Comment by elprans** [comment]
It's not an issue for the version of nodejs being tested (4.2.6), as this value is set to infinity by default: https://nodejs.org/dist/latest-v4.x/docs/api/http.html#http_agent_maxsockets
