### ISSUE TITLE
Curio stream example

### ISSUE THREAD

**Issue by dabeaz** [MagicStack/vmbench#3]
The curio stream example should use .read(102400) instead of .read() to match the comparable asyncio code.  Yes, it makes a difference in the performance.

**Comment by 1st1** [comment]
Fixed in eb6e89409296443369b73f5a0475ef8903700037. I'll rerun the benchmarks.

**Comment by 1st1** [comment]
It's indeed a bit faster! I've updated the blog post. See also http://magic.io/blog/uvloop-blazing-fast-python-networking/tcp-bench.html
